### ISSUE TITLE
Question contenu Carte de référence

### ISSUE THREAD

**Issue by Heisenberk** [Heisenberk/Go-Language#1]
# Faut-il détailler l'utilisation des principales bibliothèques (standards et tierces)? 

Solutions possibles : 
- Décrire les bibliothèques standards et tierces sans exemple de code
- Décrire les bibliothèques standards et tierces avec explication de ligne de code (comparable à Bases du langage)

# Faut-il détailler toutes les possibilités du langage dans la carte de référence? 

- Goruntines, Canaux, Tickers, Mutex, Processus sont proposés par le langage Go mais ne sont pas forcément dans les explications de nos sources tel que [tutorial-Go](https://www.tutorialspoint.com/go/index.htm)

**Comment by hal91190** [comment]
Pour les bibliothèques, je préfère qu'il y ait des exemples de code. Par contre, il faut se limiter aux cas d'usage simples.
Pour la seconde question, la réponse est non. On se limite également aux cas d'usage typiques du langage sans aller dans les détails trop pointus. La difficulté est de placer la barre au bon endroit.

**Comment by Heisenberk** [comment]
D'accord, nous ferons en sorte de respecter cela. 
Merci pour la réponse.
